### ISSUE TITLE
Performing regex matching on db engine itself

### ISSUE THREAD

**Issue by ivergara** [Quantco/datajudge#10]
Currently, the VarcharRegexConstraint requests all the values in a column and transfers them to the application to perform the matching.

[PostgreSQL](https://www.postgresql.org/docs/9.3/functions-matching.html) and [MSSql server](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms187489(v=sql.105)) do support executing (limited) regex pattern matching in the engine itself.

It'd be very nice to see how we could make use of that. Or maybe to create a more simple version using the db, while keeping the existing one for cases when the db cannot handle the given pattern.

**Comment by kklein** [comment]
Sqlalchemy comes with a regexp matching since version 1.4:
https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.regexp_match

We'd have to figure out whether this works as intended on our supported backends.
