### ISSUE TITLE
Bug: Raw condition string does not work for snowflake columns

### ISSUE THREAD

**Issue by YYYasin19** [Quantco/datajudge#106]
When using the following setup (just an example, probably transferable to other cases as well)
```py3
req = WithinRequirement.from_table(...)
req.add_date_between_constraint(column_name, "1900-01-01", "2100-01-01")
```
the following SQL is produced (roughly):
```sql
SELECT schema.table.column_name
FROM schema.table
WHERE (column_name >= 1900-01-01) and (column_name <= 2100-01-01)
```
The missing `'` around the dates throws an SQL compilation error, at least for Snowflake ❄️ .

This is caused at a pretty general location [in the code](https://github.com/Quantco/datajudge/blob/9f2d5e21de4ddeb4ddd91af35c0d947bc8a28816/src/datajudge/db_access.py#L777):
```py3
column = ref.get_column(engine)
    new_condition = Condition(
        conditions=[
            Condition(raw_string=f"{column} >= {lower_bound}"), # ... missing here
            Condition(raw_string=f"{column} <= {upper_bound}"),
        ],
        reduction_operator="and",
    )
```

I'm somewhat surprised this works for other `Condition`s or databases, I thought that most SQL dialects require one to wrap string arguments in single quotes.

Should we just make this wrapping dependent on the type of the bounds?
I also think that _always_ using single-quotes should not break anything, at least for the few test cases I tried it out.

let me know, I can draft a quick fix :)

**Comment by kklein** [comment]
Hi @YYYasin19 !
Could it be that you are missing a single quote inside of the double quote?
See here[0] for an example
https://datajudge.readthedocs.io/en/latest/api/datajudge.html#datajudge.WithinRequirement.add_date_between_constraint

**Comment by YYYasin19** [comment]
Oh, didn't see that in the docs, because of the font!
Thanks!
