### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ivergara** [Quantco/datajudge#121]
Seen in CI while doing integration testing

> Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)

**Comment by kklein** [comment]
I think this can be closed, right @ivergara ?

**Comment by ivergara** [comment]
It's not showing up, thus can be closed.
