### ISSUE TITLE
Refine `AssertionError` message for `NRowsMinGain` and `NRowsMaxGain` constraints

### ISSUE THREAD

**Issue by jak-ket** [Quantco/datajudge#161]
When the constraint `NRowsMinGain` is not met, the following exemplary `AssertionError` is thrown:

> AssertionError: TAB_NEW has 0.30231844350740233 of #rows of TAB_OLD. It was supposed to increase at least 0.5.

I find this message misleading as TAB_NEW has actually 130 % of #rows of TAB_OLD, or 30 % increase in #rows. 

As a minimal refinement I would suggest to replace the string "of #rows of" with "relative gain in #rows compared to" in the `assertion_text ` of `NRowsMinGain`.

This would change the message to
> AssertionError: TAB_NEW has 0.30231844350740233 relative gain in #rows compared to TAB_OLD. It was supposed to increase at least 0.5.

Additionally, one could express the numbers as percentage by multiplying `relative_gain` as well as `self.min_relative_gain` with 100, adding "%" to the string and omitting the "relative". That would give us:
> AssertionError: TAB_NEW has 30.231844350740233 % gain in #rows compared to TAB_OLD. It was supposed to increase at least 50 %.

Similarly, it would probably make sense to change the error message in `NRowsMaxGain`.

**Comment by ivergara** [comment]
Would have been great to deal with the loss functions too

**Comment by kklein** [comment]
What do you mean by loss function?

**Comment by ivergara** [comment]
I might be wrong, but the constraint [`NRowsMaxLoss`](https://github.com/Quantco/datajudge/blob/0d4ba07f619563306caa3b8413145c3bc5c0f597/src/datajudge/constraints/nrows.py#L69) probably has similar issues. Same with `NRowsMinLoss`.

**Comment by jak-ket** [comment]
When the constraint `NRowsMaxLoss` is not met, the following exemplary `AssertionError` is thrown:

> AssertionError: The #rows from TAB_NEW have decreased by 0.30231844350740233 compared to table TAB_OLD. It was only allowed to decrease 0.25. 

I don't think that the message is semantically misleading. However, we could harmonize the format with the recent refinements:

> AssertionError: The #rows from TAB_NEW have decreased by **30.231844350740233 %** compared to table TAB_OLD. It was only allowed to decrease **by 25 %**.

I am happy to create a new issue and PR tackling this.

I don't seem to find a constraint named `NRowsMinLoss`. Can you please point me towards it?

**Comment by kklein** [comment]
> I don't seem to find a constraint named NRowsMinLoss. Can you please point me towards it?

There is none. :)

**Comment by kklein** [comment]
@ivergara We tackled this in https://github.com/Quantco/datajudge/pull/165 - great catch!
