### ISSUE TITLE
Add README TOC

### ISSUE THREAD

**Issue by jonashaag** [Quantco/datajudge#19]
What do you think about adding a TOC to the README? It's pretty long already.

Note that GitHub itself has a Markdown TOC but it's kind of hidden visually: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/

What I'm suggesting is to add something that looks like this: https://github.com/thlorenz/doctoc

It would be autogenerated by something like https://github.com/marketplace/actions/toc-generator or https://github.com/ekalinin/github-markdown-toc#toc-generation-with-github-actions.

**Comment by kklein** [comment]
> It's pretty long already.

It is! At the same time it's expected to be shortened considerably by this PR [0].

Thanks for the references! I would suggest to see whether the remaining length of the readme will 'justify' a toc once the documentation content has been adapted/moved. In general, we intend to move a lot of information to readthedocs.

Does that sound good to you?

[0] https://github.com/Quantco/datajudge/pull/17

**Comment by kklein** [comment]
Can this be closed?
