### ISSUE TITLE
Typo in datajudge/docs/source/examples/example_dates.rst:156

### ISSUE THREAD

**Issue by anciubotaru** [Quantco/datajudge#227]
Typo in [datajudge/docs/source/examples/example_dates.rst:156](https://github.com/Quantco/datajudge/blob/c52ad81fd2a568b74b6c5f14dbbb14d87ca09305/docs/source/examples/example_dates.rst?plain=1#L156)

Pleas -> Please

**Comment by ivergara** [comment]
Thank you for pointing this out.
