### ISSUE TITLE
Re-implement KS test in sqlalchemy expression language API

### ISSUE THREAD

**Issue by YYYasin19** [Quantco/datajudge#29]
Hey, 

to track this task, I'd like to open a new issue for the future.
Currently, the Kolmogorov Smirnov test has been implemented in pure SQL, which was already a big win (cf. #28 ).

To get even more independence from different database internals and remove some of the clunky implementation details (e.g. string replacements in `mssql` table references to fit into the SQL template) it would be helpful to convert the SQL query into [sqlalchemy expression language](https://docs.sqlalchemy.org/en/14/core/tutorial.html).

This shouldn't be too hard, since:
- the expression language API has been used throughout the project as well, so there is a lot of referene
- the test consists mostly of `with`-query steps and commonly-available functions
- this is completely seperated from the rest of the project (hence the `good first issue` label) and consists of "just" translating an SQL query into sqlalchemy expressions

Thanks in advance for whoever might be participating (even if it's just future me).

**Comment by jonashaag** [comment]
> Thanks in advance for whoever might be participating (even if it's just future me).

![image](https://user-images.githubusercontent.com/175722/176730597-0df5406c-c713-4f77-86c2-f42598e8cd1b.png)
