### ISSUE TITLE
Isolation of snowflake tables

### ISSUE THREAD

**Issue by kklein** [Quantco/datajudge#49]
Status quo:
* We have a single snowflake database in use for CI. 
* Our integration tests set up and tear down tables before and after running the tests, respectively. Across executions of the tests, the tables are always created with the same table name and within the same schema, e.g. `dbo` and `int_table1`[0].
* Whenever CI is triggered simultaneously by more than one event within a timespan of ~10', at least one of the CI runs will almost surely fail (False Negative) due to interference between both runs. After all, they rely on the same database and same tables.

Solution ideas:
1. Give tables (pseudo-)unique names, e.g. `int_table1_{timestamp}` instead of `int_table1`. Even though our test suite comes with a teardown, we might need to set up a regular cleanup of the snowflake database since the integration test teardown itself might occasionally fail.
2. Make use of locking[1] for the tables at hand. This would make a CI test execution wait for all previously started to finish.
3. Implement a mechanism to only create/write to tables if not already existent. This would rely on the assumption that a table is immutable/doesn't change over time. This assumption should in principle be true as of now but might not always be. I imagine that we might need to adapt/get rid off the teardown behaviour. 

Any thoughts, opinions and suggestions are welcome!

[0] https://github.com/Quantco/datajudge/blob/main/tests/integration/conftest.py#L62-L68
[1] https://docs.snowflake.com/en/sql-reference/transactions.html#resource-locking

**Comment by ivergara** [comment]
I do like option 3, it'd make the runtime for the snowflake tests slightly faster. I did consider this a long time ago but decided against it at the time. I agree that the assumption of immutable tables rather holds, and if we need to change then, well... we know we have to clean the database manually first.

However, probably option 1 is the cleanest one. Just one question, do you see improper cleanup executions that need a manual cleanup?

**Comment by kklein** [comment]
> Just one question, do you see improper cleanup executions that need a manual cleanup?

On second look I think that I was wrong and that we don't actually have any teardown code - albeit it presumably being easy to add:
https://github.com/Quantco/datajudge/blob/main/tests/integration/conftest.py#L54-L59

Assuming that we add teardown code to the table fixtures, there is still a case distinction to be made:
* If all tests pass, teardown should work and no remainder be left in the database.
* If all failing tests pass with `AssertionError`s, teardown should work and no remainder be left in the database.
* If some tests fail due to exceptions other than `AssertionError`s it might be that the fixture won't be able to run its post-`yield` code.

**Comment by ivergara** [comment]
We don't have teardown, but we prepare the state by dropping any existing table first.

For postgres and mssql in CI it doesn't really matter since we start from fresh databases with each run. The preparation step in `_handle_table` function is a bit more important when local testing and developing new tests.

In snowflake, recreating the tables each time implies some "considerable" slowing down for the full test. Now, since we don't delete the data in the end, and recreate the tables at the beginning, we have the "worst" situation in a way. We pay for storage, and we make the tests slower. Not that it's too worrisome, just pointing it out.

Now, my question is, do we really need/want teardown code?
