### ISSUE TITLE
Output: Round numbers for cleaner output

### ISSUE THREAD

**Issue by YYYasin19** [Quantco/datajudge#88]
We recently had the following output in our project
```
E   AssertionError: <schema1>.<table> has 0.21356959387452668 of #rows of <schema2>.<table>.
It was only allowed to increase 0.2102716914986854.   
```
I know that the error that `0.21` should be `1.21` has been fixed, but I'd like to think about ways we could make the user output more readable.

#### Naive idea:
Allow the user to set the rounding, e.g. when the user allows an increase of `0.1` than they maybe don't want to see `0.1000023423020234` as output. (hard to make it right for _all_ cases)

#### Another solution
Easy: Just show the numbers up to the first change! This would print
```
E   AssertionError: <schema1>.<table> has 0.213 of #rows of <schema2>.<table>.
It was only allowed to increase 0.21.   
```
here

and we could even just convert to percentages
```
E   AssertionError: <schema1>.<table> has 21.3% of #rows of <schema2>.<table>.
It was only allowed to increase 21%.
```

**Comment by kklein** [comment]
> Another solution

Sounds great! :)
