### ISSUE TITLE
DateMin constraint including tolerance

### ISSUE THREAD

**Issue by YYYasin19** [Quantco/datajudge#98]
Hey, 

I have a situation where I want to validate that almost all dates in a column are sensible, i.e., between 1900 and 2050.
Initially, I thought about the `DateMin` constraint; unfortunately, it does not currently support specifying a tolerance. 
Since only ~99% of values fulfill this specification, I can't use the regular `DateMin` constraint.

Is there another way to achieve this with the current suite, or should we/I refactor `DateMin` to allow for tolerance?

**Comment by kklein** [comment]
> Is there another way to achieve this with the current suite

Nothing neat comes to mind.

> or should we/I refactor DateMin to allow for tolerance?

I guess that that's an option - in which case one should do the same for `NumericMin` and `NumericMax`. An alternative could also be to imitate the `NumericBetween` constraint for dates. That way, you could directly express how much of the mass you'd at least expect between boundaries.

**Comment by kklein** [comment]
Haha, so have I, it seems. :)

Can this be closed, then?

**Comment by YYYasin19** [comment]
> Haha, so have I, it seems. :)
😄 

> Can this be closed, then?
Yes :)
