### ISSUE TITLE
Confusing error message in RowMatchingEquality

### ISSUE THREAD

**Issue by jonashaag** [Quantco/datajudge#99]
I'm comparing two tables that have 0% identical rows, and I'm getting:

```
AssertionError: 1.000000 > 0.01 of rows matched between OLD_TABLE and NEW_TABLE
```

Shouldn't this be "NOT matched"?

**Comment by kklein** [comment]
Thanks for bringing this up.

I think the assertion text is very misleading. I'd prefer it if it was of the form: `$actual_mismatch_rate` > `$max_mismatch_rate` of rows differed among a match of $size_overlap rows.
where
* `$size_overlap` is the number of rows which have equal values in `matching_columns` in both tables
* `$actual_mismatch_rate` is the number of rows from both tables which have equal values in `matching_columns` but differ in at least one other column, divided by `$size_overlap`.

I can get to that tomorrow.

**Comment by jonashaag** [comment]
Yes that makes sense!

**Comment by kklein** [comment]
I'll look into that later today!
